### ISSUE TITLE
Update to conform to TOML 0.5.0

### ISSUE THREAD

**Issue by rmobis** [ToruNiina/toml11#10]
Recently, [a new spec for TOML was published](https://github.com/toml-lang/toml/blob/master/CHANGELOG.md#050--2018-07-11). Are there any plans to update toml11 to conform to this new spec? If so, I'd be willing to work on PRs to implement at least a few of the changes.

**Comment by ToruNiina** [comment]
Yes, I think it is good to make toml11 compatible with toml 0.5.0 in the next release.
But currently I have no concrete plan. I may need to refactor some portion of the parser stuff.

Pull requests are welcome! If you have any idea to improve toml11, please send it.

**Comment by ToruNiina** [comment]
I released version 2.0.0 that conforms toml v0.5.0!
Not only the new syntax, also the quality of error messages increased a lot. Check it out!

The effect of changing version is I think enough small. I needed no change except around `datetime` objects to make the integrated tests pass.
