### ISSUE TITLE
Set CMake Standard Cache Variables

### ISSUE THREAD

**Issue by jwillikers** [ToruNiina/toml11#101]
When setting the CMake standard and extensions variables, cache variables are usually used instead of normal variables.
Also, `CXX_STANDARD_REQUIRED` is the target property, but I think that the CMakeLists.txt meant to set the `CMAKE_CXX_STANDARD_REQUIRED` variable.
Below is the current section in the CMakeLists.txt.
```cmake
set(CMAKE_CXX_EXTENSIONS OFF)
if(NOT DEFINED CMAKE_CXX_STANDARD)
    set(CMAKE_CXX_STANDARD 11)
endif()
set(CXX_STANDARD_REQUIRED ON)
```
I would propose to make the CMakeLists.txt more like the following:
```cmake
set(CMAKE_CXX_STANDARD 11 CACHE STRING "The C++ standard whose features are requested to build all targets.")
set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "Boolean describing whether the value of CXX_STANDARD is a requirement.")
set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL "Boolean specifying whether compiler specific extensions are requested.")
```

**Comment by ToruNiina** [comment]
Thank you for the helpful suggestion. You are right. It works perfectly.
If you would make a pull request, it's always welcome.

**Comment by jwillikers** [comment]
Okay, I'll make another pull request 👍
