### ISSUE TITLE
table parse problem

### ISSUE THREAD

**Issue by yanggthomas** [ToruNiina/toml11#105]
Hi! Thanks for your library.
I found a small problem with dot key tables.
 
Suppose we have a dot key table 

fruit.apple="red"
```
auto table=toml::find(data,"fruit");
auto color=toml::find<std::string>(table,"apple");

```
works.

However,
`auto color=toml::find<std::string>(table,"fruit","apple")`
fails.

**Comment by ToruNiina** [comment]
Hi,
I tried to reproduce the problem with the following code,

```toml
# example.toml
fruit.apple = "red"
```

```cpp
#define TOML11_COLORIZE_ERROR_MESSAGE                                               
#include "toml.hpp"                                                                 
#include <iostream>                                                                 
                                                                                    
int main()                                                                       
{                                                                                
    const auto data = toml::parse("example.toml");                               
    const auto x = toml::find<std::string>(data, "fruit", "apple");              
    std::cout << x << std::endl;                                                 
    return 0;                                                                    
} 
```

And it outputs `red`, successfully.

Could you tell me what kind of the error did you get? Like, the compilation failed, an exception was thrown, or got a completely different value?

**Comment by yanggthomas** [comment]
Hi, thanks for your quick reply.
It seems this proplem arises with another table.

```
#test.in
[example]
vegetable="tomato"

fruit.apple="red"
```

```
int main()
{
  auto data=toml::parse("test.in");
  auto st1=toml::find<std::string>(data,"example","vegetable");
  auto st2=toml::find<std::string>(data,"fruit","apple");
  std::cout<<st1<<" "<<st2<<std::endl;
}
```
I got

```
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: [error] key "fruit" not found
 --> test.in
   | 
 1 | [example]
   | ^-------- in this table
```
I checked the toml documentation again, this is due to my understanding about toml. Toml is treating fruit as a subtable rather than a standalone table. It is a bit annoying that toml doesn't have an indication for end of table. Thanks for your time.

**Comment by ToruNiina** [comment]
Hi, thank you for the detailed explanation.

I found that the error message looks like pointing to the first table. It actually points the top-level table that starts at the first character of the file. It is very confusing.

I added an additional check while throwing an error message in the following commit. It will explicitly say "not found in the top-level table" if the error region points to the top-level table.

https://github.com/ToruNiina/toml11/commit/d11e42ca7ef1ece1871adba570b83cc8835f7658

It still points the same position, but the error message will be a bit clearer, I think.

```console
[error] key "a" not found in the top-level table
 --> example.toml
   | 
 1 | [example]
   | ^-------- the top-level table starts here
```
