### ISSUE TITLE
Is there any way to serialize TOML prettier?

### ISSUE THREAD

**Issue by KangJH** [ToruNiina/toml11#106]
Hello, 
First of all, thank you for making this cool function.
I have a simple question.
Is there any way to save toml file with pretty Indentation? 
I'm using toml::format() to update my original toml file after modifying values . One problem is this function remove all the Indentation in the file.
Do you have good idea to solve this situation?

**Comment by ToruNiina** [comment]
Sorry, currently, it does not have that functionality.
You need to implement your own visitor function to format TOML values. But it is almost equivalent to write a full serializer...

Although it does not provide the feature currently, I'm positive to add it. These days I'm a bit busy, so I don't know when I can work on it.

**Comment by KangJH** [comment]
OK, Thank you for sharing current status and have positive thinking of it.
I will close the issue.
