### ISSUE TITLE
Default ctor is required for custom types

### ISSUE THREAD

**Issue by RudenkoRNK** [ToruNiina/toml11#108]
Hi!
I noticed that "get" method for containers like vector uses method "resize". I was frustrated by that, because some of my structures does not have default ctors. Maybe resize can be replaced with back_inserter?

**Comment by ToruNiina** [comment]
You are right. That is inconvenient.

I implemented that feature in the branch [do-not-require-default-ctor-108](https://github.com/ToruNiina/toml11/tree/do-not-require-default-ctor-108).
After some checking, I will merge it to master. Check it out!

**Comment by RudenkoRNK** [comment]
Cool!! Thanks))

**Comment by RudenkoRNK** [comment]
Everything works fine with vectors, but now I run into same problem with maps.
"get" method for maps uses brackets for creating new entries:
`map[key_type(kv.first)] = ::toml::get<mapped_type>(kv.second);`
This also requires default ctor for mapped_type. Is it possible to replace it with something like:
`map.insert(std::pair(key_type(kv.first), ::toml::get<mapped_type>(kv.second)));`?

**Comment by ToruNiina** [comment]
Sorry, I forgot about maps. I fixed it and pushed to the master branch. I also updated tests to check with a struct without default constructor.

**Comment by RudenkoRNK** [comment]
Thanks a lot 👍
