### ISSUE TITLE
Add support for <filesystem>

### ISSUE THREAD

**Issue by amasciotta** [ToruNiina/toml11#113]
Hello! First of all, thank you for this great library, it's fantastic!

Would it be possible to add support for `<filesystem>` related types, mostly `std::filesystem::path`? I would love to pass a `path` directly to the `parse` function!

I'm aware that `filesystem` is a C++17 library, but it should be feasible to enable additional overloads with suitable `#ifdef`s.

Thank you!

**Comment by ToruNiina** [comment]
That sounds like it would come in handy!
I will implement it. But could you wait a while? I have a lot of stuff to do these days.

**Comment by ToruNiina** [comment]
Sorry for the late action, I implemented it.
