### ISSUE TITLE
Expose library's version via macro

### ISSUE THREAD

**Issue by ddavness** [ToruNiina/toml11#114]
Some C/C++ libraries expose a macro defining their current version. What about adding one to `toml11`, too? For example:

```cpp
#define TOML11_VERSION "3.4.0"
```

Another alternative might be

```cpp
#define TOML11_VERSION_MAJOR 3
#define TOML11_VERSION_MINOR 4
#define TOML11_VERSION_PATCH 0
```

**Comment by ToruNiina** [comment]
That sounds nice. I prefer the second option because it is easier (to me) to use it in preprocessor. I will add it in the next release.

**Comment by ToruNiina** [comment]
Added in a344668fa293ce371bec6112c4e6979a7dcad042, [v3.5.0](https://github.com/ToruNiina/toml11/releases/tag/v3.5.0).
