### ISSUE TITLE
Please fix README.md code.

### ISSUE THREAD

**Issue by toge** [ToruNiina/toml11#118]
Hello. I just start to use toml11. It's great library!

When I try to execute codes in README.md, I found a problem.
Please fix this problem.

In https://github.com/ToruNiina/toml11#tomlget

```
const auto  name  = toml::find<std::string>(fruit, "apple");
```
I think following code is valid.
```
const auto  name  = toml::find<std::string>(fruit, "name");
```

**Comment by ToruNiina** [comment]
Thank you for finding the problem! You are right, it should be `"name"`.
Would you like to make a Pull Req to fix this?

**Comment by halfelf** [comment]
Hi @ToruNiina . I've submitted a PR to fix this and other problems in the same example.
