### ISSUE TITLE
modify values

### ISSUE THREAD

**Issue by WangXu18** [ToruNiina/toml11#126]
How do I modify the value of the toml file in my cpp code? Is there such an interface?

**Comment by ToruNiina** [comment]
There are several ways to do that.
```cpp
const toml::value v1(42);                 // 1. construct from c++ value

toml::value v2;
v2 = "foobar";                            // 2. insert a value

toml::value v3 = toml::parse("example.toml");
v3.at("table").at("key") = "value";       // 3. basically the same as 2, `at` returns a toml::value&.
v3.at("array").as_array().push_back(3.14) // 4. cast to a non-toml value(here std::vector) and modify it
```

**Comment by WangXu18** [comment]
i mean,how can i modify the key's value that has been defined in toml file just whit a function or some interface which has defined in toml11.

**Comment by WangXu18** [comment]
for example,in some sense,i read some information from test.toml ,and,i used it。this part is clear in your readme.md document。
well,sometimes,i also need write some information to the test.toml to update information.
example:
test.toml
test = 10

after some operations in my cpp:
test.toml
test = 123

**Comment by ToruNiina** [comment]
If I understand correctly, do you want to modify the toml file, not the data on memory? You can serialize toml file by passing `toml::value` to iostream or fstream.

```cpp
toml::value v = toml::parse("test.toml");
v.at("test") = 123;
std::cout << std::setw(80) << v;
```

Note that you may need to add some io-manipulators(like `setw`) to format it in a readable form.

**Comment by WangXu18** [comment]
yes，i want modify the toml file.and,the method you give me in the email don't work,maybe,i need write some function to modify datas and save it to toml file by myself...

**Comment by ToruNiina** [comment]
Could you explain what happens or paste the error message here?

I'm writing the full version of my solution. At least it works in my environment. Does it work?

```cpp
#include "toml.hpp"
#include <iostream>

int main()
{
    toml::value v = toml::parse("test.toml");
    v.at("test") = 123;
    std::cout << std::setw(80) << v;
    return 0;
}
```

```toml
# test.toml

test = 10
```

**Comment by WangXu18** [comment]
it seems that only the data in the memoey is modifed
| |
wangxiaoyong1993
|
|
wangxiaoyong1993@126.com
|
签名由网易邮箱大师定制
On 8/31/2020 18:29，Toru Niina<notifications@github.com> wrote：

Could you explain what happens or paste the error message here?

I'm writing the full version of my solution. At least it works in my environment. Does it work?

#include"toml.hpp"
#include<iostream>intmain()
{
    toml::value v = toml::parse("test.toml");
    v.at("test") = 123;
    std::cout << std::setw(80) << v;
    return0;
}
# test.tomltest = 10

**Comment by WangXu18** [comment]
it seems that only the data in the memory is modified.
![image](https://user-images.githubusercontent.com/26597463/91711801-1d396800-ebb9-11ea-9852-f278a1415093.png)

**Comment by WangXu18** [comment]
Left is the value of Consol,right is the value of toml file,and the programe is as same with your

**Comment by ToruNiina** [comment]
It's because it outputs the contents on `std::cout` for quick checking. You can change it to `std::ofstream("test.toml")`.

**Comment by ToruNiina** [comment]
I mean, you can output the content to a file with the following code.
```cpp
#include "toml.hpp"
#include <iostream>

int main()
{
    toml::value v = toml::parse("test.toml");
    v.at("test") = 123;
    std::ofstream ofs("test.toml");
    ofs << std::setw(80) << v;
    return 0;
}
```

**Comment by WangXu18** [comment]
ok,thanks.with io stream ,it's really can be resolve.and i have a suggest,after the function named parse called,the object returned has many information about the toml file on memory,so,if there are some inner functions to deal with it,perhaps,it's will be more efficient.
Thank you.
