### ISSUE TITLE
Proposal: Make toml11_BUILD_TEST Off by default

### ISSUE THREAD

**Issue by MoAlyousef** [ToruNiina/toml11#129]
Hello
Great library. I think testing shouldn't be enabled by default. Changing the option shouldn't break any builds, and it should make integrating the library as a CMake project/subdir easier (seeing that testing requires boost). 
I've created a fork which turns off testing. If you're ok with the proposal, I'll create a pull request.
Thank you

**Comment by ToruNiina** [comment]
Hi,
Thank you for the suggestion. That makes sense.
I think it is okay if we have a note about it on README.

**Comment by MoAlyousef** [comment]
Yes.
I've added a note in the README and created a PR #130

**Comment by ToruNiina** [comment]
I have just merged it. Thank you!
