### ISSUE TITLE
Feature request: Add helper macros

### ISSUE THREAD

**Issue by hg-zt** [ToruNiina/toml11#139]
In `nlohmann/json` we have https://github.com/nlohmann/json#simplify-your-life-with-macros
so that I could simply define both serializer and deserializer in one line:

```cpp
namespace my_ns {

struct MyType {
  int some_value;
  OtherSerializableType some_obj;
}

NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(MyType, some_value, some_obj);
}
```

which makes it possible to convert from/to
```json
{
   "some_value": 1,
   "some_obj": { ... }
}
```

I'd like to have similar macros to generate `into_toml` and `from_toml`  for simple structs. Something like `TOML11_DEFINE_NON_INTRUSIVE`.

**Comment by ToruNiina** [comment]
Sounds nice. I think I can implement it quickly.
But, because of the current implementation, the usage would be slightly different from the code shown.

**Comment by ToruNiina** [comment]
I'm struggling with the difference in the preprocessor implementation between gcc/clang and MSVC. If you are using gcc/clang, here is the working code. If you are using MSVC, please wait a bit more.

https://github.com/ToruNiina/toml11/blob/auto-conversion-macro/toml/macros.hpp

**Comment by glebm** [comment]
Looks like Microsoft added a preprocessor flag that enables well-behaved `__VA_ARGS__` in the recent versions of their compiler?

Perhaps toml11 could require the flag to be set?

https://docs.microsoft.com/en-us/cpp/build/reference/zc-preprocessor?view=msvc-160

**Comment by ToruNiina** [comment]
Thank you very much @glebm ! It works!
