### ISSUE TITLE
Assert: Call of std::string::back() on an empty std::string when parsing empty comments

### ISSUE THREAD

**Issue by Naios** [ToruNiina/toml11#141]
0dafa7ee42739311ba6d455a41700febdeb11263

The MSVC iterator debug checks cought a call to `std::string::back()` on an empty `std::string`.

The following example is probably sufficient to reproduce it
```toml
#
a = 1
```

https://github.com/ToruNiina/toml11/blob/0dafa7ee42739311ba6d455a41700febdeb11263/toml/region.hpp#L346-L348

**Comment by ToruNiina** [comment]
Thank you for reporting the issue!
I added additional checks.

**Comment by ToruNiina** [comment]
I confirmed that the patch passes the CI and merged it.
Thanks again!
