### ISSUE TITLE
Empty array is formatted anonymously inside a table

### ISSUE THREAD

**Issue by Naios** [ToruNiina/toml11#142]
0dafa7ee42739311ba6d455a41700febdeb11263

When formatting an empty array inside a table the name of the array is not present in the table which leads to parsing errors when parsing the formatted toml again.

```cpp
  toml::value val;
  val["empty"] = toml::array{};
  std::cout << toml::format(val) << std::endl;
```

```toml
[]
```

---

```cpp
  toml::value val;
  val["empty"] = toml::array{1};
  //                        ^^^
  std::cout << toml::format(val) << std::endl;
```

```toml
empty = [1]
```

**Comment by ToruNiina** [comment]
Thank you very much for the information.
I have reproduced and fixed it. I'm now waiting CI on [this branch](https://github.com/ToruNiina/toml11/tree/issue-142). After confirming it passes, I will close it.

Thank you again!

**Comment by Naios** [comment]
Thank you for fixing this issue so fast.

You could catch similar issues that are related to parsing -> formatting -> parsing -> crash in the future, by using **fuzzing**. This would detect wrong formatting, crashes and misbehaviour through sanitizers quite easy.

oss-fuzz provides a free infrastructure if you are interested: https://github.com/google/oss-fuzz
