### ISSUE TITLE
How do I preserve comments for my own type?

### ISSUE THREAD

**Issue by shaperilio** [ToruNiina/toml11#146]
I have defined a type:
```
namespace My {
    struct CustomType {
        int value = 5;
        std::string outputPath = "./";
    };
}
```
and I've defined conversion to/from Toml in this way:
```
namespace toml {
    template<>
    struct from<My::CustomType> {
        static My::CustomType from_toml(value const & v) {
            My::CustomType o;
            o.level = find<int>(v, "level");
            o.outputPath = find<std::string>(v, "outputPath");
            return o;
        }
    };
    template<>
    struct into<My::CustomType> {
        static toml::table into_toml(My::CustomType const & o) {
            toml::basic_value<toml::preserve_comments> level = o.level;
            level.comments().push_back("This is what level is.");

            toml::basic_value<toml::preserve_comments> outputPath = o.outputPath;
            outputPath.comments().push_back("This is where cool things will happen.");

            std::cout << outputPath << std::endl; // <-- Up to here, the comments are preserved.

            toml::table result; <-- This will strip my comments
            result["level"] = level;
            result["outputPath"]= outputPath;
            return result;
        }
    };
}
```

The return type of `toml::table` strips comments. So what should the return type of `into_toml` be?

**Comment by ToruNiina** [comment]
`toml::basic_value<toml::preserve_comments>`.

`toml::table` is an alias to the `std::unordered_map<std::string, toml::value>`. As you know, `std::unordered_map` does not have any space to contain comments, so it strips them. `toml::basic_value<toml::preserve_comments>` has additional container to store comments. But note that, if you convert `toml::basic_value<toml::preserve_comments>` to normal `toml::value`, the comments would be lost, because normal `toml::value` is not able to store those data.

**Comment by shaperilio** [comment]
Ok, but I also changed the function to return `std::unordered_map<std::string, toml::basic_value<toml::preserve_comments>>` and this also resulted in the comments being lost. That has nothing to do with the storage capacity of `std::unordered_map`; the comments are in the object values, not in the map itself.

How do I define a custom conversion that keeps comments?

**Comment by ToruNiina** [comment]
I mean, you need to use `toml::basic_value<toml::preserve_comments>` as a return value of `into_toml`.
The following should work. I've tested it with `g++ -std=c++11 main.cpp -Wall -Wextra -Wpedantic`, with g++-7.5.0, on Ubuntu 18.04.

```cpp
#include "toml.hpp"
#include <iostream>

namespace My {
    struct CustomType {
        int level = 5;
        std::string outputPath = "./";
    };
}


namespace toml {
    template<>
    struct from<My::CustomType> {
        static My::CustomType from_toml(value const & v) {
            My::CustomType o;
            o.level = find<int>(v, "level");
            o.outputPath = find<std::string>(v, "outputPath");
            return o;
        }
    };
    template<>
    struct into<My::CustomType>
    {
        static toml::basic_value<toml::preserve_comments> into_toml(My::CustomType const & o) {
            toml::basic_value<toml::preserve_comments> level = o.level;
            level.comments().push_back("This is what level is.");

            toml::basic_value<toml::preserve_comments> outputPath = o.outputPath;
            outputPath.comments().push_back("This is where cool things will happen.");

            toml::basic_value<toml::preserve_comments> result;
            result["level"] = level;
            result["outputPath"]= outputPath;
            return result;
        }
    };
}

int main()
{
    My::CustomType c;
    toml::basic_value<toml::preserve_comments> v{{"custom", c}};
    std::cout << v << std::endl;
// [custom]
// #This is where cool things will happen.
// outputPath = "./"
// #This is what level is.
// level = 5

    return 0;
}
```

**Comment by shaperilio** [comment]
Ah great, thanks. You should add this to the docs, and maybe consider aliases for types that preserve comments (or making that the default).

I think the comment handling ability of your library is a big plus over others. Given that TOML is precisely tailored towards human readability, I personally rank that quite highly.

**Comment by ToruNiina** [comment]
Thank you for the suggestion and I have added a sample code for this.
I also think I can make this feature more useful when we change the major version.
