### ISSUE TITLE
Formatting integer values in hexadecimal notation

### ISSUE THREAD

**Issue by amasciotta** [ToruNiina/toml11#149]
Hello! I would like to serialize to file a `toml::array`. However, I would like to serialize some integers (but not all of them) contained in my data structure using the hexadecimal notation (e.g. 0xA1B2C3D4). Is there a way to do so?

More in general it would be great to have the possibility to specify a custom formatting for some of the values, using a syntax like the `fmt` library.

**Comment by ToruNiina** [comment]
Sorry, currently it does not have an API to do that. For an excuse, hexadecimal, octal nor binary numbers were not in the TOML spec when I started this library.
But yeah, we need to make it possible. It can be done via the serializer options or adding format-related flags in a toml::value.
These months I didn't have much spare time nor mental rest, but I think the situation will improve, hopefully. At least, I want to find a way to do this.

**Comment by ToruNiina** [comment]
I have released v4.0.0 and now it has format information.

The API is different from `{fmt}`, but you can now set format flags for each value.

For more detail, please refer to [the documentation](https://toruniina.github.io/toml11/docs/features/serialize/#specifying-formats).
