### ISSUE TITLE
Tag v3.6.0 version numer is 3.5.0

### ISSUE THREAD

**Issue by oPiZiL** [ToruNiina/toml11#151]
```
#define TOML11_VERSION_MAJOR 3
#define TOML11_VERSION_MINOR 5
#define TOML11_VERSION_PATCH 0
```

**Comment by ToruNiina** [comment]
Yes, that is a mistake, and is already fixed at the current commit. Changing the tag and github release files changes commit hash and affects on many things, so I cannot fix it. I will make a checklist to avoid the same mistakes.
If you have a nice idea, please share with me.

**Comment by oPiZiL** [comment]
Maybe you can write a script to generate RELEASE asserts automaticlly   
VERSION define can be a templated file lke `toml.hpp.in`, version number can be extracted from some CHANGELOG.md  
so before you can release, you MUST prepare an updated CHANGELOG.md file, then execute the build script(can be write with shell, which turn  `toml.hpp.in` into  `toml.hpp`)  
Above can ensure you modify VERSION number only in CHANGELOG.md

**Comment by ravipathuri** [comment]
As in https://github.com/ToruNiina/toml11#constructing-a-tomlvalue , in case of constructing a table, the syntax looked like
toml::value v{{"foo", 42}, {"bar", 3.14}, {"baz", "qux"}};
To the above constructed table, how can we append one more key value pair. Is there such a provision in the current implementation?

**Comment by ToruNiina** [comment]
version numbers in CMake and hpp are semi-automated now.
