### ISSUE TITLE
Document validation?

### ISSUE THREAD

**Issue by trapexit** [ToruNiina/toml11#153]
Are there any suggestions regarding the validation of data in a toml doc? It seems that one either needs to fully validate the doc up front in what could be a very tedious set of code given there doesn't appear to be any API to help with it or do so while consuming individual elements. The latter feels complicated by how errors are handled. If find_or is used the default is returned even if the value exists and is found bad due to a catch(...) in get_or. Even if find_or allowed errors through it isn't possible to have a list of find_or calls and catch all errors in one go which would force the user to fix each issue one at a time and rerun.

**Comment by ToruNiina** [comment]
Let me confirm some points. There are mainly two stage of validation, syntax validation and data validation. In the syntax validation stage, an invalid toml value will be reported. In the data validation stage, missing values and unused values will be reported. You mean, you want to have a utility function that does data validation, right?

Currently, such a utility function is not provided as a part of this library. In principle, we can implement it without stopping the program execution using `bool toml::basic_value::contains(const std::string&)` and `toml::value_t toml::basic_value::type()`, like

```cpp
bool has_data(const toml::value& v,
              const std::vector<std::pair<std::string, toml::value_t>>& ls)
{
    bool is_ok = true;
    for(const auto& [key, type] : ls)
    {
        if( ! v.contains(key))
        {
            std::cerr << toml::format_error("[error] missing key",
                                            v, "should have " + key) << std::endl;
            is_ok = false;
        }
        else if(v.at(key).type() != type)
        {
            std::cerr << toml::format_error("[error] unexpected type",
                    v.at(key), "should be " + toml::stringize(type)) << std::endl;
            is_ok = false;
        }
    }
    return is_ok;
}
```

Or, you can also use [type conversion feature](https://github.com/ToruNiina/toml11#conversion-between-toml-value-and-arbitrary-types) to handle recursive parameter sets in a (slightly) easier way.

```cpp
struct foo
{
    int         a;
    double      b;
    std::string c;

    void from_toml(const toml::value& v)
    {
        // Here, we can check if all the values are in `v` and
        // print an error message if the condition is not satisfied
        this->a = toml::find<int        >(v, "a");
        this->b = toml::find<double     >(v, "b");
        this->c = toml::find<std::string>(v, "c");
        return;
    }
};
```

**Comment by trapexit** [comment]
Thanks. This is what I'm doing but yes it would be nice to have some DSL or set of functions that could verify the data. I might just end up building such a thing for my usecase.
