### ISSUE TITLE
Populate the table header in a separate step

### ISSUE THREAD

**Issue by ravipathuri** [ToruNiina/toml11#155]
Thanks for the clarification in https://github.com/ToruNiina/toml11/issues/154 . Populating the key-value pairs is understood. But how can we populate the table header in a separate step?

And as i understand, when we push the key value pairs and print the same, the order in which the key-value pairs are generated can be random("please correct me if I am wrong") as the type is std::unordered_map. If that is the case, how can I initialize a "toml::value" that would take std::map as the type?

_Originally posted by @ravipathuri in https://github.com/ToruNiina/toml11/issues/154#issuecomment-813278234_

**Comment by ToruNiina** [comment]
In toml11, there is no difference between tables and non-table values. You can just add a table, as a subtable.

```cpp
#include "toml.hpp"
#include <iostream>

int main()
{
    toml::value v{{"foo", 42}, {"bar", 3.14}, {"baz", "qux"}};

    v["hoge"] = {{"name", "piyo"}};

    std::cout << v << std::endl;
    // baz = "qux"
    // bar = 3.14
    // foo = 42
    //
    // [hoge]
    // name = "piyo"

    return 0;
}
```

To use `std::map` as an underlying container, you need to explicitly pass the container type to `toml::basic_value`, as described [here](https://github.com/ToruNiina/toml11#customizing-containers).

```cpp
toml::basic_value<toml::preserve_comments, std::map> sorted_value;
```

**Comment by ravipathuri** [comment]
Thanks for the clarification
