### ISSUE TITLE
Mark project files as SYSTEM when not standalone

### ISSUE THREAD

**Issue by andrewkcorcoran** [ToruNiina/toml11#158]
Currently user code compiled with -Wshadow is failing when trying to use toml due to warnings in toml/types.hpp. CMake has an inbuilt mechanism (SYSTEM) to suppress warnings in header files of third party libraries. This should be enabled for toml to prevent issues in header files from breaking users who use the library from source. See https://github.com/microsoft/GSL/blob/main/include/CMakeLists.txt as an example.

```
toml/types.hpp:44:24: error: declaration of ‘boolean’ shadows a global declaration [-Werror=shadow]
toml/types.hpp:24:7: note: shadowed declaration is here
```

**Comment by ToruNiina** [comment]
Thank you for reporting the issue, I reproduced it.
If I'm not mistaken, the reason of the warning is the name of `enum class toml::value_t;` and `typedef`s. I think it is difficult to avoid the problem without changing the name of enumerator names and type names, but it is also difficult to change the typenames for the sake of backward compatibility. So I think I need to, as you said, inform users to set `SYSTEM` in `target_include_directories` to avoid this issue. I will add it to the README. I will also consider to add some `pragma`s to avoid this issue automatically.

I also found that it passes the tests if we reduced the level of warning as `-Wshadow=local` in a particular version of gcc in my local machine. I will examine a bit more and add the warning to the CI build if possible.

Thank you again!

**Comment by andrewkcorcoran** [comment]
It should be possible to suppress the warnings within the tomll11 CMake
code on users behalf. Take GSL as an example, it detects when the code is
being used directly by a user and sets the SYSTEM attribute automatically
on all GSL include directories. The same should be possible here with very
little work.

**Comment by ToruNiina** [comment]
I have suppressed the error related to `-Wshadow` at the level of soruce code, and added `-Wshadow` to `tests/CMakeLists.txt` to check it automatically on CI services.

**Comment by andrewkcorcoran** [comment]
Hi toml is failing to compile again with -Werror=free-nonheap-object. The root solution to this is that we need to make all toml files as system when toml is included as a subdirectory. Can we reopen this please.
