### ISSUE TITLE
Types deduced as const when using as_table() in a range-based for-loop .

### ISSUE THREAD

**Issue by thor-sr** [ToruNiina/toml11#175]
In the following example it seems the const-version of `as_table` is being called when we would expect the non-`const` version to be called. In the function `bar` I get a compiler error complaining that I'm calling `foo` with a `const toml::value&`.

```cpp
void foo(toml::value& non_const_value) {
  // Do something
}

void bar() {
  toml::value val;
  for (auto& el : val.as_table()) {
    auto& child_val = el.second;
    foo(child_val); // Compiler error here, the type ofchild_val is const toml::value& but function expected non-const reference
  }
}

```

There seems to be no difference between `for (auto& el : val.as_table())` and `for (const auto& el : val.as_table())` in this case.

This problem also occurs when using structured bindings (`for (auto& [child_key, child_val] : val.as_table())`).

I'm running on Ubuntu 18.04 and compiling with GCC 7.5.

For anyone having the same problem, as a temporary workaround you can use `const_cast`:
```cpp
  for (auto& el : val.as_table()) {
    auto& child_val = el.second;
    foo(const_cast<toml::value&>(child_val));
  }
```

**Comment by ToruNiina** [comment]
I couldn't reproduce the error on my Ubuntu 18 desktop using g++ 7.5.0 with the following code.
```console
$ cat issue175.cpp
#include <iostream>
#include <sstream>

#include "toml.hpp"

void foo(toml::value& v)
{
   if(v.is_table())
   {
       v["foobar"] = toml::value{2.71828};
   }
   else
   {
       std::cout << v << std::endl;
   }
   return ;
}

int main()
{

   toml::value val = toml::table{
       {"foo", 42},
       {"bar", 3.14},
       {"baz", "qux"},
   };

   for (auto& el : val.as_table())
   {
       auto& child_val = el.second;
       foo(child_val);
   }
   return 0;
}
$ g++-7 issue175.cpp -std=c++11 # it just works.
```


 If you are still there, could you put the error message in your case?

**Comment by thor-sr** [comment]
I just tried your snippet and it works for me too when using `g++-7 issue175.cpp -std=c++11`.

I also tried copying that code into my working environment and it produces an error there. I just changed it to the following
```cpp
void foo(toml::value& v)
{
   if(v.is_table())
   {
       v["foobar"] = toml::value{2.71828};
   }
   else
   {
       std::cout << v << std::endl;
   }
   return ;
}

int bar()
{

   toml::value val = toml::table{
       {"foo", 42},
       {"bar", 3.14},
       {"baz", "qux"},
   };

   for (auto& el : val.as_table())
   {
       auto& child_val = el.second;
       foo(child_val);
   }
   return 0;
}
```

And the error I get it
```
[build] /home/thor-sr/project/test.cpp: In function ‘int bar()’:
[build] /home/thor-sr/project/test.cpp.cpp:130:12: error: binding reference of type ‘toml::value& {aka toml::basic_value<toml::preserve_comments, tsl::ordered_map, std::vector>&}’ to ‘const toml::basic_value<toml::preserve_comments, tsl::ordered_map, std::vector>’ discards qualifiers
[build]         foo(child_val);
[build]             ^~~~~~~~~
[build] /home/thor-sr/project/test.cpp.cpp:105:6: note:   initializing argument 1 of ‘void foo(toml::value&)’
[build]  void foo(toml::value& v)
[build]       ^~~
[build] ninja: build stopped: subcommand failed.
```

This is a CMake project using C++17 and GCC 7.5. 
I am adding toml11 to my project as part of an interface library
```cmake
add_library(${TARGET_MY_PROJECT_COMMON_3RD_LIBS} INTERFACE)
target_include_directories(
  ${TARGET_MY_PROJECT_COMMON_3RD_LIBS}
  INTERFACE
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/spdlog/include> # log
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/toml11> # configuration
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/ordered_map/include> # configuration
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/glm> # configuration
)
```
and `TARGET_MY_PROJECT_COMMON_3RD_LIBS` then gets added to the main library 
```
target_link_libraries(
  ${TARGET_MY_PROJECT_MAIN}
  PUBLIC ${TARGET_MY_PROJECT_COMMON_3RD_LIBS}
)
```

Please let me know if you have any ideas what the problem might be. As I mentioned before, I can currently work around this issue with `const_cast` so the library is still completely usable, but it would be nice to get rid of it. And thanks for the great library, I'm enjoying using it so far :smiley:

**Comment by ToruNiina** [comment]
It seems that `tsl::ordered_map` returns `const std::pair<Key, Value>` from its iterator and you need to call `iter.value()` to write into `iter->second`. I think this is the reason why it became constant.

https://github.com/Tessil/ordered-map#differences-compared-to-stdunordered_map

But in a range-based for loop, we basically cannot call it. A proxy iterator might be helpful that wraps `tsl::ordered_map::iterator` and returns `std::pair<Key, Value&>` as its `value_type`.

**Comment by ToruNiina** [comment]
Based on the above comment, the conclusion is:
- the problem does not originate from toml11, but ordered_map that is used as a table class in your configuration instead of the default `std::unordered_map`.
- the problem cannot be workarounded by modifying the source code of toml11

Some ideas:
- Use a traditional for loop, `for(auto iter = table.begin(); iter!=table.end(); ++iter) {auto& val = iter.value()}` instead, as suggested in https://github.com/Tessil/ordered-map#differences-compared-to-stdunordered_map
- Implement a proxy iterator that wraps `tsl::ordered_map::iterator` that returns `std::pair<const Key, Value&>` from its `operator*` and use it in the range-based for loop.

**Comment by thor-sr** [comment]
Thank you, now it all makes sense. Good to know the error is not coming from this library.
I appreciate you taking the time to look at my issue and thank you for the ideas. I will most certainly try them out :+1:
