### ISSUE TITLE
toml::get ambiguous with user-defined toml::from/from_toml for Eigen types (again)

### ISSUE THREAD

**Issue by maspri** [ToruNiina/toml11#177]
This is a similar issue to #159.

Eigen 3.4.0 has added support for accessing 1D Arrays via random access iterator. This means Eigen::Matrix now has the typedefs _value_type_ and _iterator_ causing [is_container](https://github.com/ToruNiina/toml11/blob/1dc09d0332cc5da1ffc1145ad11bade69ec75b3b/toml/traits.hpp#L208) to be true.

Together with a user-defined _toml::from_  this will cause [toml::get (L330)](https://github.com/ToruNiina/toml11/blob/1dc09d0332cc5da1ffc1145ad11bade69ec75b3b/toml/get.hpp#L330) and [toml::get (L448)](https://github.com/ToruNiina/toml11/blob/1dc09d0332cc5da1ffc1145ad11bade69ec75b3b/toml/get.hpp#L448) to both be applicable (or [toml::get (L439)](https://github.com/ToruNiina/toml11/blob/1dc09d0332cc5da1ffc1145ad11bade69ec75b3b/toml/get.hpp#L439) if _toml_from_ was defined).

The same code example as #159 can be used as minimal example.

**Comment by ToruNiina** [comment]
I added a condition to check if there is a specialized conversion function.
After checking CI, I will merge it (currently circle CI is failing but it is a known issue and I will fix it later. I will merge after checking if all others pass)

**Comment by expnn** [comment]
Come to the same situation while implementing conversion between toml value and ``boost::regex`` according to the [documentation](https://github.com/ToruNiina/toml11#conversion-between-toml-value-and-arbitrary-types). 

```c++
namespace toml {

template<>
struct from<boost::regex>
{
    template<typename Comment,
        template<typename ...> class Table,
        template<typename ...> class Array>
    static boost::regex from_toml(const ::toml::basic_value<Comment, Table, Array>& v) {
        auto repr = toml::get<std::string>(v);
        return boost::regex(repr);
    }
};

template<>
struct into<boost::regex>
{
    template<typename Comment = toml::discard_comments,
        template<typename ...> class Table = std::unordered_map,
        template<typename ...> class Array = std::vector>
    static ::toml::basic_value<Comment, Table, Array> into_toml(const boost::regex& value) {
        return value.str();
    }
};

} // toml
```
