### ISSUE TITLE
Provide CLI toml-test decoder

### ISSUE THREAD

**Issue by moorereason** [ToruNiina/toml11#179]
I would like to have a CLI app compatible with the [`toml-test` decoder](https://github.com/BurntSushi/toml-test#implementing-a-decoder) interface.  It takes TOML input from STDIN and outputs annotated JSON to STDOUT.

I've been doing differential fuzzing with various TOML implementations and would like to test this package.

**Comment by ToruNiina** [comment]
You can find it here.
https://github.com/ToruNiina/toml11/blob/master/tests/check_toml_test.cpp

Also you can see the result of toml-test with the latest commit of toml11 here.
https://app.circleci.com/pipelines/github/ToruNiina/toml11?branch=master
