### ISSUE TITLE
Mishandling of document with only NULL bytes

### ISSUE THREAD

**Issue by moorereason** [ToruNiina/toml11#181]
Given a TOML document of any(?) length made with only NULL bytes, `toml11` returns a valid, empty document:
```
$ echo -n '\x00\x00\x00\x00' | check_toml_test
{}
```
I expect this input to be invalid.

AFAICT if there are any non-NULL bytes after the leading NULL bytes, the parser given an error as expected.

Found while doing differential fuzzing against [`go-toml/v2`](https://github.com/pelletier/go-toml/tree/v2).

**Comment by ToruNiina** [comment]
Thank you for reporting! Historically I added this for the null terminated string, but currently we don't need this. I removed it.
