### ISSUE TITLE
Do not allow redefinition of existing table

### ISSUE THREAD

**Issue by moorereason** [ToruNiina/toml11#183]
Given this invalid example from the [TOML spec](https://toml.io/en/v1.0.0#table):
```toml
[fruit]
apple.color = "red"
[fruit.apple]  # INVALID
```
`toml11` accepts the document as valid:
```
$ echo "[fruit]\napple.color = \"red\"\n[fruit.apple]" | check_toml_test | jq
{
  "fruit": {
    "apple": {
      "color": {
        "type": "string",
        "value": "red"
      }
    }
  }
}
```
Tested with commit bf2384d8da9cdd91bdc51092452e02cc982af0c7.

PS - I've submitted [new tests cases](https://github.com/BurntSushi/toml-test/pull/104) to the `toml-test` suite for this.

**Comment by ToruNiina** [comment]
Fixed in e60442c. Thank you!
