### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by lukash** [ToruNiina/toml11#184]
Hello, could you make a new release please?

I'm particularly needing 21732fce as this started causing build failures with `-Werror=free-nonheap-object` on Fedora Rawhide.

Thanks!

**Comment by ken-matsui** [comment]
Hi @ToruNiina,

I understand you are busy, but I'd be grateful if you could publish a new release containing the [commit](https://github.com/ToruNiina/toml11/commit/21732fce459911d4da0214baff52af7c8c48cc9f) :)

Thank you!

**Comment by ToruNiina** [comment]
I released v3.7.1. Sorry for the late response.
