### ISSUE TITLE
How to parse and iterate non const string fragment?

### ISSUE THREAD

**Issue by krishna116** [ToruNiina/toml11#191]
How to parse follow non const string fragment and iterate the key-values?
```C++
std::string str  = R"({color = "red", font = "mono"})";
std::string str  = R"([color = "red", font = "mono"])";
std::string str  = R"(val = [color = "red", font = "mono"])";
std::string str  = R"(val = {color = "red", font = "mono"})";

//auto value = toml::parse(str?) ...
```
I do this because if I want to embed toml to other grammar string, for example embed toml string to json, or embed json string to toml, just like two level grammar:
```JSON
{
    "json-obj": "toml-key1 = \"toml-value1\" toml-key2 = \"toml-value2\""
}
```
then it will be useful.

Thanks.

**Comment by ToruNiina** [comment]
You can pass (not only `std::ifstream` but also) a `std::istream` to `toml::parse`. So, you can pass a `std::istringstream` constructed from your `std::string` to `toml::parse` and you can parse the content of the string as a TOML format.

When you pass a `std::istream` to `toml::parse`, you can optionally pass a "filename" that will be used in an error message like the following:

```cpp
#include <sstream>
const std::string str = json_file.at("json-obj").as_string();
std::istringstream iss(str);
const toml::value toml_data = toml::parse(iss, /*optional -> */ "json-obj");
```
