### ISSUE TITLE
ability to not throw exceptions

### ISSUE THREAD

**Issue by rollraw** [ToruNiina/toml11#195]
is there possibility to disable exceptions and/or use alternative way for debugging (like assertions etc)?

**Comment by xahon** [comment]
I'd rather use error-codes/statuses instead of exceptions too

**Comment by ToruNiina** [comment]
I have released v4.0.0 and now it supports `toml::try_parse`. It returns `toml::result<toml::value, std::vector<toml::error_info>>` and does not throw `toml::syntax_error`.

For more detail, please refer the [document](https://toruniina.github.io/toml11/docs/features/parsing_files/#tomltry_parse).
