### ISSUE TITLE
How to remove element from toml::value

### ISSUE THREAD

**Issue by ifateev** [ToruNiina/toml11#201]
Hello everyone! I want to remove some values from my toml::value but this code seems like have no effect:
```
toml::value m_table;
auto table = m_table.as_table();
auto erased = table.erase(std::string(key));
```
what am I doing wrong?

**Comment by ToruNiina** [comment]
Since `auto` copies the variable, `table` that you modified on the second line is not the table in `m_table`. You need to use `auto&` to take a reference to it.

```cpp
toml::value m_table;
auto& table = m_table.as_table(); // take a reference that points a table inside `m_table`
auto erased = table.erase(std::string(key));
```
