### ISSUE TITLE
Rejects definition of parent of table array

### ISSUE THREAD

**Issue by jorisvr** [ToruNiina/toml11#211]
Toml11 rejects the following valid TOML document:
```
[[a.b]]
x = 1

[a]
y = 2
```

It prints the following error message:
```
what(): [error] toml::insert_value: table ("a") already exists.
 --> ../toml-test/tests/valid/table/array-implicit-and-explicit-after.toml
   |
 1 | [[a.b]]
   | ~~~~~~~ table already exists here
 ...
 4 | [a]
   | ~~~ table defined twice
```

This applies to the latest release (v3.7.1) as well as the current master branch 22db720ad55c3470c4d036ae74be35e68c761845 .

The rejected TOML document is similar to the following valid example from the TOML 1.0.0 spec:
```
[x.y.z.w]
[x] # defining a super-table afterward is ok
```
The difference is that this example implicitly creates table `x` through a table definition, while the rejected document implicitly creates table `a` through a table-array definition. However this should not mattter. In either case, the parent table should exist as an implicit table, and a subsequent explicit definition should be allowed.

This testcase is part of toml-test: https://github.com/BurntSushi/toml-test/blob/master/tests/valid/table/array-implicit-and-explicit-after.toml

**Comment by ToruNiina** [comment]
I fixed it. Thank you!

**Comment by jorisvr** [comment]
Great, thanks. Toml11 now passes the full toml-test suite again. :+1:
