### ISSUE TITLE
How can I check if an array has an homogeneous set of values?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [ToruNiina/toml11#216]
Hi,

I'm evaluating to migrate to this library from [tomlplusplus](https://github.com/marzer/tomlplusplus) and one of the missing features I have is the [`is_homogeneous`](https://github.com/marzer/tomlplusplus/blob/7eb2ffcc09f8e9890dc0b77ff8ab00fc53b1f2b8/include/toml%2B%2B/impl/array.inl#L143-L180) API for arrays.

Is there anything similar being offered on toml11?

Thank you in advance,
Julian

**Comment by ToruNiina** [comment]
There is no equivalent function, but you can get type information with `type()` member function. Using this, you can determine if a `toml::value` is homogeneous as follows.

```cpp
bool is_homogeneous_array(const toml::value& v)
{
    if(!v.is_array()) {return false;}
    if(v.as_array().empty()) {return true;}
    const toml::value_t type_of_front_elem = v.as_array().front().type();
    for(std::size_t i=1; i<v.size(); ++i)
    {
        if(v.at(i).type() != type_of_front_elem) {return false;}
    }
    return true;
}
```

**Comment by julianxhokaxhiu** [comment]
Thank you!
