### ISSUE TITLE
I'd like to retrieve uint64_t that exceed the range of int64_t

### ISSUE THREAD

**Issue by virtuald** [ToruNiina/toml11#220]
The TOML standard specifies:

> Arbitrary 64-bit signed integers (from −2^63 to 2^63−1) should be accepted and handled losslessly. If an integer cannot be represented losslessly, an error must be thrown.

python's tomli can handle arbitrary sized integers, and I'd really like to be able to read `0x8000000000000000` from a TOML file using toml11.

It seems to me that the best way to make this doable (and optional) is to provide some template overload (similar to how comments are dealt with) to modify the parsing behavior to accept a custom function or something to retrieve/store the integer value. Then a user can define how they want to store the integer.

**Comment by Bqleine** [comment]
+1, I'd also love to be able to read my uint64_t from toml without having to bother about negative values and losing half the range

**Comment by ToruNiina** [comment]
I have released version v4.0.0, allowing for changes to `integer_type`.

You can see a working example [here](https://github.com/ToruNiina/toml11/blob/main/examples/boost_multiprecision/multiprecision.cpp) of the most extreme case, where `integer_type` is `boost::multiprecision::cpp_int`.

In the similar way, you can also use `std::uint64_t`, `boost::multiprecision::int128_t`, and others.

Please refer to the [doc](https://toruniina.github.io/toml11/docs/features/configure_types/) for more detail.
