### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Conan-Kudo** [ToruNiina/toml11#221]
It's been over a year since the last release, and there seems to be a fair bit of changes since. Any chance for a new version release soon?

**Comment by ken-matsui** [comment]
@ToruNiina Could you please make a new release when you get a chance? I just need this commit: https://github.com/ToruNiina/toml11/commit/9086b1114f39a8fb10d08ca704771c2f9f247d02.

**Comment by ToruNiina** [comment]
Sorry for late. Released.

**Comment by ken-matsui** [comment]
Thanks!
