### ISSUE TITLE
When trying to use your tests / examples, there are no `*.toml` files in the repo

### ISSUE THREAD

**Issue by Smurf-IV** [ToruNiina/toml11#227]
Would be nice to see what the tests are trying to confirm against  please ?

**Comment by ToruNiina** [comment]
Here it downloads toml-lang/toml at v0.5.0 because it contains a useful example toml file.
https://github.com/ToruNiina/toml11/blob/master/tests/CMakeLists.txt#L9-L17

Very recently toml-test becomes a part of toml standard, so maybe we can remove this (unclear) test in the near future.
