### ISSUE TITLE
Does this library have any way to output TOML?

### ISSUE THREAD

**Issue by tfiner** [ToruNiina/toml11#23]
There are a handful of ostream extractor functions, but nothing I can find that converts a toml::table to a string or an ostream. This is a shame considering how nice the parsing is. 

I would have used the boost version of this library, but didn't want to wait for it to compile the world. ;) I had to kill it when ninja had all 8 cores going and each instance of the compiler had 2+GB of memory.

**Comment by ToruNiina** [comment]
Actually, I have a plan to implement a serializer to output `toml::table` in almost the same way as Boost.toml does. But these days I didn't have much time to do that.

I will re-start implemented it again. It may takes time, so please be patient for a while.

**Comment by tfiner** [comment]
Excellent! Thank you.

**Comment by ToruNiina** [comment]
Hi, I added `iostream` support and `toml::format`. I hope it helps you.
https://github.com/ToruNiina/toml11#serializing-toml-data

**Comment by tfiner** [comment]
Thank you, I'll try it out.
