### ISSUE TITLE
`toml::format` returns the wrong floating value

### ISSUE THREAD

**Issue by ups-ishii** [ToruNiina/toml11#239]
Hello! 
An unexpected string was returned when I got a string from `toml::value v(3.14)` by `toml::format`.

On:
* d4eb5f3 - (HEAD, tag: v3.8.1, origin/master, origin/HEAD)

Env:
```
% /usr/local/opt/llvm/bin/clang++ -v
Homebrew clang version 17.0.6
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
```

Code (main.cpp):
```cpp
#include "toml.hpp"
#include <iostream>
#include <string>

int main() {
  const toml::value v(3.14);
  const std::string fmt = toml::format(v);
  std::cout << "floating: " << v.as_floating() << std::endl;
  std::cout << "    op<<: " << v << std::endl;
  std::cout << "  format: " << fmt << std::endl;
}
```

Actual Output:
```
% /usr/local/opt/llvm/bin/clang++ main.cpp
% ./a.out
floating: 3.14
    op<<: 3.14
  format: 3.1400000000000001
```

Expected Output:
```
floating: 3.14
    op<<: 3.14
  format: 3.14
```

thank you!

**Comment by ToruNiina** [comment]
This may be unexpected behavior, but the value is actually correct.

In binary numbers, 3.14 cannot be expressed in a finite number of digits.
Computers use binary numbers, so we get `3.1400000000000001` when you write `3.14` as a double-precision floating point number. This value is the closest number to 3.14 of all the values that can be expressed in `double`.
cf. https://wandbox.org/permlink/RXlDyxSXM3II6q53

By default, the `toml::format` outputs the most accurate value possible. In other words, it uses `std::numeric_limits<double>::max_digits10` as its precision.
To change this setting and perform rounding on a specific digit, do the following.

```cpp
const std::string fmt = toml::format(v, /*line width = */80, /*precision = */16);
```

To print `3.1400000000000001` as `3.14`, 16 is small enough.

**Comment by ups-ishii** [comment]
Understood. I learned a lot.
Thank you very much for your very detailed explanation!
