### ISSUE TITLE
toml::format incorrectly formats an empty array of tables which fails to be parsed later on

### ISSUE THREAD

**Issue by ifexception** [ToruNiina/toml11#262]
I have a scenario where I am using Array of Tables and it can be empty in certain cases. When this occurs, toml11 will correctly parse the file and my program will initialize as the array of tables is formatted according to the toml specification.

However, during the operation of the program, the array of tables can be reset. When this occurs toml11 does not format an empty array of tables as I would expect and then throws a `bad_format` error when I later try to parse the toml file.

## Expected Behavior
Given the following toml structure in code:
```
toml::value output(
	toml::table{
		{
			"array-of-tables",
			toml::array{}
		},
		{
			"subtable",
			toml::table{}
		},
	}
);
```
`toml::format` should return:
```
[[array-of-tables]]

[subtable]
```
Which should align to the [spec](https://toml.io/en/v1.0.0#array-of-tables)

## Current Behavior
Given the following toml structure in code:
```
toml::value output(
	toml::table{
		{
			"array-of-tables",
			toml::array{}
		},
		{
			"subtable",
			toml::table{}
		},
	}
);
```
`toml::format` returns:
```
array-of-tables = 

[subtable]
```
Which throws a bad format error when parsing:
> [error] bad format: unknown value appeared
 --> test.toml
   |
 1 | array-of-tables =0x0d(CARRIAGE RETURN)
   |                  ^-- here

## Steps to Reproduce
`test.toml`:
```
array-of-tables =

[subtable]

```
C++ MRE:
```
#include <iostream>
#include <string>

#include <toml.hpp>

int main()
{
    toml::value output(
        toml::table{
            {
                "array-of-tables",
                toml::array{}
            },
            {
                "subtable",
                toml::table{}
            },
        }
    );

    auto& aot = output.at("array-of-tables");
    aot.as_array_fmt().fmt = toml::array_format::array_of_tables;
    aot.as_array_fmt().body_indent = 4;
    aot.as_array_fmt().closing_indent = 2;

    std::string asString = toml::format(output);

    std::cout << asString << std::endl;

    try
    {
        auto p = toml::parse("test.toml");
    }
    catch (const std::exception& e)
    {
        std::cerr << e.what() << "\n";
    }

    std::cin.get();
    return 0;
}

```

## Context (Environment)
Visual Studio 2022 CMake project
`toml11` installed via vcpkg
`toml11` version 4.0.0
64 bits

**Comment by ToruNiina** [comment]
thank you for the detailed explanation of the problem you met.

But actually, your example code written here contains a mistake.

In TOML, the following defines an empty table named `table` under the root table.

```toml
[table]
```

In JSON, it corresponds to

```json
{ "table": {} }
```

And, similarly, the following TOML:

```toml
[[tables]]
```

defines an empty table that is the first element of an array named `tables`.

So it corresponds to:

```json
{ "tables": [ {} ] }
```

That means that, an array named `tables` has one element and is not empty.

The TOML file you intended:

```toml
[[array-of-tables]]

[subtable]
```

corresponds the following in JSON:

```json
{
    "array-of-tables": [{}]
    "subtable":{}
}
```

And that is NOT equivalent to:

```json
{
    "array-of-tables": []
    "subtable":{}
}
```

`array-of-tables` actually contains one empty table, so is not an empty array.

Based on these, you need to add one empty table to your c++ code.

```cpp
    toml::value output(
        toml::table{
            {
                "array-of-tables",
                toml::array{ toml::table{} } // here
            },
            {
                "subtable",
                toml::table{}
            },
        }
    );
```

This returns the following:

```toml
[subtable]
[[array-of-tables]]

```

`toml::parse` also parses the file to this. You can see that the `array-of-tables` has one element.

https://wandbox.org/permlink/EndLu9HddNBw1A3K

----

That said, it is still a problem that `toml::format` outputs an invalid toml string in this case. The correct output should be the following if the array is empty.

```toml
array-of-tables = []
[subtable]
```

I have written a patch for this change. Later I will merge and then close this.

**Comment by ifexception** [comment]
Hi there,

Many thanks for your detailed response and highlighted my erroneous assumption with regards to array of tables. 

I added a `toml::table{}` to the empty `toml::array` and now formats it correctly and it addresses my original issue :)
