### ISSUE TITLE
Problem with MacOS

### ISSUE THREAD

**Issue by georgemoralis** [ToruNiina/toml11#263]
building v4 throws error in macOS

comments_fwd.hpp:267:54: error: no member named 'terminate' in namespace 'std'; did you mean 'template'?
  267 |     reference_type operator*()  const noexcept {std::terminate();}
      |                                                 ~~~~~^~~~~~~~~
      |                                                      template
/Users/runner/work/shadPS4/shadPS4/externals/toml11/include/toml11/fwd/comments_fwd.hpp:267:63: error: expected unqualified-id
  267 |     reference_type operator*()  const noexcept {std::terminate()

reference
https://github.com/shadps4-emu/shadPS4/actions/runs/10254936058/job/28370765030?pr=368

**Comment by ToruNiina** [comment]
I couldn't reproduce the problem on `macos-latest` with `maxim-lobanov/setup-xcode@v1`, `xcode-version: latest`.
cf. https://github.com/ToruNiina/toml11/actions/runs/10286743564/job/28468214952

From your description and error messages on your ci, it seems that the lack of declaration of `std::terminate` causes the problem. So I added include header `<exception>` where `std::terminate` is provided and merged it. I hope it will fix the problem.

**Comment by georgemoralis** [comment]
yes that seems to fix the issue . thanks!
