### ISSUE TITLE
No consistent order when saving large toml files

### ISSUE THREAD

**Issue by andreaskeller96** [ToruNiina/toml11#265]
Is there a way to either have the items within a table sorted or to preserve their order when parsing and saving files?

I have found the issues #133 and #111 that also ask the question but it seems the answer in 133 does not apply anymore to the newest version of the library. I need a cosnsitent way of saving large files since having the order change every time is a nightmare when dealing with versioning large files unfortunately.

Thank you for your help.

**Comment by ToruNiina** [comment]
You can use `toml::ordered_type_config` and `toml::ordered_value`.

```cpp
#include <toml.hpp>
#include <iostream>

int main(int argc, char** argv)
{
    if(argc != 2) {return 1;}

    const auto input = toml::parse<toml::ordered_type_config>(argv[1]);
    std::cout << toml::format(input) << std::endl;

    return 0;
}
```

cf. https://toruniina.github.io/toml11/docs/features/configure_types/#preserving-order-of-values-in-tables

I will add more description about it to README and the docs.

**Comment by andreaskeller96** [comment]
Perfect, thank you so much! I must've missed the section in the docs, sorry about that.
