### ISSUE TITLE
Key parsing errors should show the error position

### ISSUE THREAD

**Issue by xaxousis** [ToruNiina/toml11#27]
When parsing an invalid file, the error should show where the parser died.

For example the following raises an exception `toml::syntax_error`  with the message `[error] toml::parse_key: the next token is not a key`. There is no way to get where what went wrong in the file.

```toml
[ a test]
```

For the specific issue, I narrowed the code down to :
https://github.com/ToruNiina/toml11/blob/83bf83b6dd9b209d4eb3633e19e36bce106e9bb2/toml/parser.hpp#L820-L826

We can replace the last line with:
```c++
    return err(format_underline("[error] toml::parse_key: ", loc, "is not a valid key"));
```

Which then would store the following message in the exception:
```
[error] toml::parse_key: 
 --> ../tests/res/dev.toml
 41 | [a test]
    | ^---------- is not a valid key
```

An other solution would be to throw a `syntax_error` directly, as done there:
https://github.com/ToruNiina/toml11/blob/83bf83b6dd9b209d4eb3633e19e36bce106e9bb2/toml/parser.hpp#L898-L899

There are several other places where this kind of behaviour could be implemented.

**Comment by ToruNiina** [comment]
You are right. It is good to have an informative error message. And your suggestion is really helpful.

Do you have a time and the will to implement it? I'm now doing a different stuff to improve error messages around dotted-keys, so fixing this would be late.

**Comment by xaxousis** [comment]
I'll try to work on this some time in the week.

**Comment by xaxousis** [comment]
I'm closing this for now as this specific issue have been dealt with. I suppose other missing error reports will show up eventually.
