### ISSUE TITLE
std::localtime error in VS2017.3 (Preview)

### ISSUE THREAD

**Issue by patrikhuber** [ToruNiina/toml11#5]
Hi!

Thanks for this great project, it seems like one of the best header-only modern C++ TOML APIs out there! :-)

I've got a compilation error when compiling with VS2017, 15.3.0 Preview:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	C4996	'localtime': This function or variable may be unsafe. Consider using localtime_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	toml-test	projects\toml-test\toml11\toml\datetime.hpp	71	

The line in question is `std::tm* t_ = std::localtime(&t);`.

I think this is probably a longstanding warning that got turned into an error in VS2017.
I tried to fix it but haven't gotten too far yet: Changing it into `std::localtime_s` doesn't work as that function doesn't exist - there exists one called `localtime_s` from C11 (without the `std::` prefix) but it does not take 1 argument.

**Comment by ToruNiina** [comment]
Hi, thank you for the issue.
As you pointed out, `localtime` is not thread-safe.

I'm not sure it is the best way to use C11 function because this is a C++11 project and C++11 is not compatible with C11. But it is also true that the problem should be fixed.

I think you can avoid the problem by doing this.
```cpp
std::tm t_;
localtime_s(std::addressof(t), std::addressof(t_));
```
A similar problem might occur with `gmtime` and can be fixed in the same way (with `gmtime_s`, also since C11).

I will add a workaround for this problem, but it possibly take some time.

**Comment by patrikhuber** [comment]
Hi!

The error seems a bit weird actually - I got it reproducibly but now it's gone for some reason. I first thought it depends on some VS project settings, whether this results in an error or not, so if you're in a CMake generated VS project file (with default settings), it behaves differently than in a VS generated project. But now for some reason it currently works in both. (And I didn't pull your fix yet). I am not sure at this point.

Agreed that a C11 function might also not be the best idea if it is not available on at least all the major recent compilers, but even then a standard C++ function would be better.

**Comment by rathaROG** [comment]
Hi @patrikhuber! How do you fix this?

**Comment by patrikhuber** [comment]
Hi @rathaROG, the error disappeared for me - not sure why. But ToruNiina also committed somethhing that should fix it, see above.

**Comment by patrikhuber** [comment]
I think we can close this, I didn't have any issues with toml11 in VS2017 since. Thanks!
