### ISSUE TITLE
Question regarding include

### ISSUE THREAD

**Issue by khoitd1997** [ToruNiina/toml11#51]
Hi, thank you for the work you have been putting into toml11, it's really nice. I just want to have a quick question about including toml11 in a project, currently ``#include "toml11/toml.hpp"`` is used, I was wondering why is it not simply ``#include "toml11.hpp"``? Are the files in the directory ``toml`` potentially necessary for using the library?

**Comment by ToruNiina** [comment]
I'm glad to hear that!

The files in the directory `toml` are necessary. The codes are split into multiple header files (just like the boost), so toml11 is not a single-file header-only library. Actually, `toml.hpp` just includes the files in `toml` directory. So you need to add the whole `toml` directory somewhere you want (possibly under your project, as a git-submodule or plain copy).

**Comment by khoitd1997** [comment]
Thank you for the detailed response, I understand it now
