### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by khoitd1997** [ToruNiina/toml11#57]
I recently tried ``make test`` with the newest release ``v2.2.2``, and the following tests fail:
```
The following tests FAILED:
	 26 - test_parse_file (Failed)
	 27 - test_serialize_file (Failed)
	 28 - test_parse_unicode (Failed)
```
Do these tests matter or are they important?

**Comment by ToruNiina** [comment]
Since it uses the files provided by [toml-lang/toml](https://github.com/toml-lang/toml) repository, you need to download the repository to run those tests.

See detail here. https://github.com/ToruNiina/toml11#running-tests

**Comment by khoitd1997** [comment]
Sorry, I didn't see that line for some reasons, the test works fine now.
