### ISSUE TITLE
Including toml.hpp in multiple translation units

### ISSUE THREAD

**Issue by usernameiwantedwasalreadytaken** [ToruNiina/toml11#7]
Hi, and thanks for the awesome project.

I don't know if I'm doing something wrong, but if I `#include <toml11/toml.hpp>` in more than one translation unit, I get linker errors:

```
manifest.obj : error LNK2005: "class std::unordered_map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class toml::value,struct std::hash<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,struct std::equal_to<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class toml::value> > > __cdecl toml::parse(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?parse@toml@@YA?AV?$unordered_map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@Vvalue@toml@@U?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@Vvalue@toml@@@std@@@2@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z) already defined in config.obj
```

I think I should only include a forward declaration of toml11 symbols in the second source file, but I could not find one.

I'm on Windows, compiling with Clang, using Visual Studio 2017 Community libraries and headers.

Thanks in advance.

**Comment by usernameiwantedwasalreadytaken** [comment]
I was able to "fix" this by using this:

```
#define TOML11_PARSER
#include <toml11/toml.hpp>
namespace toml { Table parse(const std::string& filename); }
```

instead of just `#include <toml11/toml.hpp>` in the second translation unit.

**Comment by ToruNiina** [comment]
Hello. thank you for using this project and telling me this issue.

It's awkward but I didn't test it well with multiple translation units.
I found the bug that you pointed out. The commit `3f1b431` may fix it.

Best,
Niina

**Comment by usernameiwantedwasalreadytaken** [comment]
Thanks.

**Comment by patrikhuber** [comment]
Hehe, I just hit this missing inline too, I was still on an older toml11 version :-)
May I ask why you changed the rest of this file in 3f1b431 (e.g. change to `const char*` from `std::string`) and not just add the missing `inline`, which fixes it?
