### ISSUE TITLE
using numbers as find() argument

### ISSUE THREAD

**Issue by peterritter** [ToruNiina/toml11#79]
the toml::find() function seems to allow any number of strings (keys) as argument but no numbers. So to access values withing tables of tables of tables  this seems to work, such as

int max_conn = toml::find<int>(toml_root, "database", "connection_max");

but what if I want to access an array element? Then I can't use a string key - I'd have to use a positional number, like:

int port_2 = toml::find<int>(toml_root, "database", "ports", 2 );

where "ports" refers to an array of port numbers - and I want to retrieve the port at position 2. Is there any reason why arguments to toml::find() can only be strings?  I think it would be great if every value in a toml file had its own 'path' consiting of strings and numbers, so that we can access each value directly without roundabout syntax.   This approach could also be used for modifying values.

**Comment by ToruNiina** [comment]
Hi,
Sorry for the late reply. It sounds nice.

I've written some codes you suggested. It seems to work. I need to add some more test cases and it may take time, but after that, I think I can merge it.

**Comment by ToruNiina** [comment]
I'm terribly sorry for the late action but finally I have merged the feature to the master branch. closing.
