### ISSUE TITLE
floating point parse error

### ISSUE THREAD

**Issue by peterritter** [ToruNiina/toml11#80]
I got an error with this :

flt5 = 1e06

it's supposed to be valid since it comes from:
https://github.com/toml-lang/toml

the error is:

 62 | flt5 = 1e06
    |           ^- expected newline, but got '6'.

**Comment by ToruNiina** [comment]
In the [`fp-exp-leading-zeros`](https://github.com/ToruNiina/toml11/commits/fp-exp-leading-zeroes) branch, the feature is implemented and tested. It seems that the feature will be released in the next version of TOML with high probability, so it will be merged into master soon.

**Comment by ToruNiina** [comment]
In the last release of toml11, `TOML11_USE_UNRELEASED_TOML_FEATURES` is introduced. By `#define`-ing it, you can use post-v0.5.0 features of TOML such as leading zeroes in exponent parts of floats.

https://github.com/ToruNiina/toml11#unreleased-toml-features
