### ISSUE TITLE
Custom conversion doesn't work

### ISSUE THREAD

**Issue by htrefil** [ToruNiina/toml11#83]
I tried to define a custom specialization of `toml::from` for my type, but it ends up with a compile time error.

Here's the code:

```
#include "toml11/toml.hpp"

enum class animal {
	DOG,
	CAT,
};

namespace toml {

template<>
struct from<animal> {
	animal from_toml(const value& value) {
		return animal::DOG;
	}
};

}

int main(int argc, char** argv) {
	auto data = toml::parse(argv[1]);
	auto a = toml::find<animal>(data, "a");
}
```

Apart from a bunch of template substitution failure errors, I get

toml11/toml/get.hpp:415:3: note:   template argument deduction/substitution failed:
toml11/toml/get.hpp:259:26: error: invalid application of ‘sizeof’ to incomplete type ‘toml::into<animal>’
          std::size_t S = sizeof(::toml::into<T>)>
                          ^~~~~~~~~~~~~~~~~~~~~~~
toml11/toml/get.hpp:259:48: error: could not convert template argument ‘<expression error>’ from ‘<type error>’ to ‘long unsigned int’
          std::size_t S = sizeof(::toml::into<T>)>

Compiled with g++ 8.3.0 with -std=c++17.
Using the latest toml11 cloned from GitHub.

Is this a bug or am I doing something wrong?

**Comment by jcmoyer** [comment]
I think the documentation is incorrect (`from_toml` should be static), see this test for correct usage: https://github.com/ToruNiina/toml11/blob/master/tests/test_extended_conversions.cpp#L38-L57

Also, I'm not sure if it's intended, but I was getting similar compiler errors until I also added a specialization for `toml::into`.

**Comment by ToruNiina** [comment]
Thank you @htrefil for the report!
And thank you @jcmoyer for the PR and finding out the problem!

This is a bug.
As you pointed out, there is a defect in the code and it requires conversion in both directions even if only one direction is needed. I've just fixed that and will push it soon.
