### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by cmaughan** [ToruNiina/toml11#87]
The error reporting is nice, but for tools that need to present parse errors to users, it would be nice if the parse_exception could contain a list of line numbers and error strings associated with them.  That way a tool that compiles a toml file can highlight and show line errors without having to parse the whole syntax error string.

**Comment by ToruNiina** [comment]
You are right. Those values should be in the exception class. I will implement it.

**Comment by cmaughan** [comment]
Awesome :)

**Comment by cmaughan** [comment]
And FWIW, when the error is in the exception, this error report will highlight the correct line ;)
![image](https://user-images.githubusercontent.com/120447/67797598-ea46b500-fa79-11e9-82f8-2607cd2f62c4.png)

**Comment by ToruNiina** [comment]
All the `toml::exception`s now (not yet released, but) have `location()` member method that returns `toml::source_location` which represents where the error happens.
