### ISSUE TITLE
internal compiler error with gcc-7.3.1

### ISSUE THREAD

**Issue by patrikhuber** [ToruNiina/toml11#9]
Hi!

With gcc-7.3.1, I am suddenly getting an internal compiler error when using toml11. With gcc-7.2, everything still seems fine.

```
[ 12%] Building CXX object examples/CMakeFiles/fit-model.dir/fit-model.cpp.o
In file included from /home/patrik/eos/3rdparty/toml11/toml.hpp:39:0,
                 from /home/patrik/eos/include/eos/core/LandmarkMapper.hpp:27,
                 from /home/patrik/eos/examples/fit-model.cpp:23:
/home/patrik/eos/3rdparty/toml11/toml/get.hpp: In substitution of ‘template<class T, toml::value_t vT, typename std::enable_if<((vT == Unknown) && toml::detail::is_map<T>::value), std::nullptr_t>::type <anonymous> > T toml::get(const toml::value&) [with T = std::unordered_map<std::__cxx11::basic_string<char>, toml::value>; toml::value_t vT = <missing>; typename std::enable_if<((vT == Unknown) && toml::detail::is_map<T>::value), std::nullptr_t>::type <anonymous> = <missing>]’:
/home/patrik/eos/include/eos/core/LandmarkMapper.hpp:77:88:   required from here
/home/patrik/eos/3rdparty/toml11/toml/get.hpp:44:69: internal compiler error: unexpected expression ‘check_type<std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, toml::value, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, toml::value> > > >’ of kind template_id_expr
 template<typename T, toml::value_t vT = toml::detail::check_type<T>(),
```

The error seems to happen just from the `#include "toml.hpp"`.

I'm building the default example from my open-source library [eos](https://github.com/patrikhuber/eos).

**Comment by patrikhuber** [comment]
Hmm, I'm actually not 100% sure about this bug.
It compiles fine on `g++-7 (Ubuntu 7.3.0-16ubuntu3~16.04.1) 7.3.0`.
But it gives an ICE on `c++ (GCC) 7.3.1 20180312` (Manjaro).

So this could be either a regression in g++-7.3.1 or a problem with Manjaro/arch's g++ build...

**Comment by patrikhuber** [comment]
I've submitted a bug report on the arch bug-tracker https://bugs.archlinux.org/task/58406, let's see.
Maybe you've got some other ideas what we could do :-)

**Comment by ToruNiina** [comment]
Hi, thank you for telling me about this problem.
I tried to reproduce the error, but I couldn't find gcc 7.3.1 in the release page https://gcc.gnu.org/gcc-7/ . Is it arch-specific version?
I also confirmed that g++-7.3.0 compiles this library without any error.

The error message looks like a problem on SFINAE. I can try some other expression to dispatch `toml::get`, but I'm not sure whether it will fix the ICE.
Currently, I don't have any good idea to solve this problem.

**Comment by patrikhuber** [comment]
Thank you for having a look. Yep, it's gcc 7.3.1 from [arch](https://www.archlinux.org/packages/core/x86_64/gcc/) (I'm using Manjaro).
I have a sort-of feeling that this is a problem of arch's gcc build, and hopefully not a regression in upstream gcc 7.3.1. So I would say let's close this for now then.

**Comment by patrikhuber** [comment]
It definitely wasn't my system at least - a user just reported this on my repo as well: https://github.com/patrikhuber/eos/issues/195

**Comment by ToruNiina** [comment]
Hi @patrikhuber , I have a good news, possibly.

I tried Manjaro by using VirtualBox, and reproduced the error you told.

I simplified SFINAE stuffs in `toml::get` and some other related functions, and now (b1a55b1), the errors disappeared. It compiles fine with gcc-7.3.1, and all the tests passes (at least on my VM).

Please try it.
Thank you for using this product.

**Comment by patrikhuber** [comment]
I think arch/Manjaro fixed their ICE in their latest update - it seems like with `gcc-7.3.1 20180406` even the "old" (before the fix) toml11 version is compiling again.
But anyway I think you were able to simplify lots of things while patching this, so that's great :-)
