### ISSUE TITLE
Unused variable warning

### ISSUE THREAD

**Issue by blockparty-sh** [ToruNiina/toml11#94]
```
toml/combinator.hpp:46:20: warning: 
      unused variable 'r' [-Wunused-variable]
        const auto r = std::snprintf(
```

This could be fixed by adding:

`(void)r; // unused variable warning`

Above the assert. 

You could also just toss the sprintf inside the assert as well, which might be cleaner.

**Comment by ToruNiina** [comment]
Thank you for reporting. I confirmed it.

`(void)r;` is preferred. `snprintf` is used to format non-printing characters in hexadecimal, so it should not be skipped even if `NDEBUG` is defined.

**Comment by ToruNiina** [comment]
Would you like to make a PR to fix this?
